// English companion articles. Chinese manuscripts remain unchanged.
import { chineseArticles } from './content-zh.js';
const records = {
 'infection': ['Let’s begin with an infection', 'Follow the journey from an invading microbe to antibodies and lasting immune memory.', [
 ['A microbe reaches the entrance', 'Skin, mucus and the lining of the airways and gut provide the first barriers. If a microbe crosses them, innate immune cells respond. Neutrophils and macrophages can engulf microbes; dendritic cells carry information to lymph nodes. This early response buys time, but it cannot replace the more specific protection that develops next.'],
 ['A B cell recognises its target', 'Each B cell carries a receptor that recognises a particular molecular shape. Binding a target is an important first step, but effective activation also depends on other signals. Helper T cells can recognise material presented by the B cell and provide instructions that support its growth and differentiation. Antibody production is therefore a coordinated response, not a task performed by one cell alone.'],
 ['An early response and a longer training programme', 'Some activated B cells quickly produce antibodies, often including IgM. Others enter germinal centres in lymphoid tissue. Here, B cells multiply, refine how well their antibodies bind and undergo selection with help from follicular helper T cells. They may switch antibody class, for example to IgG or IgA. Changing class changes how the antibody works without simply changing its target.'],
 ['What remains after the infection?', 'Plasma cells are specialised antibody producers. Some can keep making antibodies for a long time. Memory B cells retain the capacity to respond again when a related target appears. The amount of antibody in the blood, the quality of a response and the number of memory cells describe related but different parts of protection.'],
 ['Where CVID can interrupt the journey', 'Many people with CVID have circulating B cells, yet make insufficient protective antibodies. Difficulties can involve activation, cooperation with other cells, maturation or the formation of effective memory. The same broad diagnosis does not mean the same molecular step is affected in everyone. This is why specialists combine infection history with several laboratory measurements.'],
 ['Neither a personal failing nor one single error', 'CVID is not caused by failing to try hard enough to stay healthy. Understanding the immune pathway helps explain why low antibodies can have more than one biological cause, and why a normal B-cell count does not necessarily mean normal antibody protection.']]],
 'multi-organ': ['Why can CVID affect more than one organ?', 'Infection defence and control of inflammation can be affected at the same time.', [
 ['The immune system also needs to stand down', 'Immunity must recognise threats, avoid attacking the body and settle after a response. These functions depend on overlapping networks of cells and signals. In CVID, reduced antibody protection may coexist with immune dysregulation. A weaker response to some microbes does not mean every immune response is weak.'],
 ['Lungs: infection is not the whole story', 'Repeated respiratory infections can damage airways, sometimes leading to bronchiectasis. A separate group of inflammatory changes can involve lung tissue, including granulomatous–lymphocytic interstitial lung disease, or GLILD. Infection and inflammation can have overlapping symptoms. A scan finding alone does not establish which process is responsible.'],
 ['Gut: a busy boundary', 'The intestine must absorb nutrients while managing constant contact with microbes. Infection, inflammation and impaired absorption can each contribute to symptoms in CVID. Persistent diarrhoea should not automatically be assigned one explanation. Research is exploring how mucosal antibodies, microbes and immune cells influence one another.'],
 ['Blood cells, spleen and lymph nodes', 'Immune responses can sometimes target platelets or red blood cells, causing immune cytopenias. The spleen and lymph nodes may enlarge when immune cells accumulate or remain activated. Enlargement has several possible causes; it is neither automatically harmless nor automatically cancer. Its meaning depends on the wider clinical assessment.'],
 ['The liver can also be involved', 'Some people develop liver abnormalities associated with immune disease or other causes. These may not produce obvious symptoms at first. Organ assessment therefore depends on the individual history and findings rather than on assuming that every person will develop the same complications.'],
 ['Why replacement antibodies are only part of the answer', 'Immunoglobulin replacement supports antibody protection, particularly against infections, but does not repair every immune-regulatory pathway. Persistent organ problems do not necessarily mean replacement treatment has failed. Infection prevention and investigation of inflammation answer different needs.'],
 ['A different combination for each person', 'The list of possible manifestations is not a prediction of your future. Some people mainly experience infections; others have overlapping complications. Long-term care follows the person’s actual pattern and how it changes.']]],
 'genetics': ['Monogenic immune deficiencies and genetic clues', 'A more specific molecular diagnosis can explain some antibody deficiencies, but every variant needs interpretation.', [
 ['CVID is an umbrella description', 'CVID brings together clinical and laboratory findings, rather than naming one defective molecule. People can share low immunoglobulins and impaired antibody responses while having different underlying biology. Genetic investigation sometimes identifies a more specific condition within this broader clinical starting point.'],
 ['When the diagnosis gains a more specific name', 'A confirmed disease-causing change in a gene can identify the pathway involved. This may clarify why antibody deficiency occurs alongside immune dysregulation or other organ findings. These defined conditions should not all be described as interchangeable CVID subtypes: some have a broader pattern of immune dysfunction.'],
 ['Genes are not the only level of explanation', 'A negative genetic test does not make symptoms less real. Current tests cannot identify every possible cause. Several genetic influences, gene regulation and other biological factors may contribute. Research methods and variant interpretation also continue to change.'],
 ['What makes a genetic clue useful?', 'Early or unusual disease, a family history, marked immune dysregulation or additional features may prompt specialist consideration of genetic testing. No single feature proves a genetic cause. The choice of investigation depends on the whole clinical picture and what a result could help clarify.'],
 ['A report is more than its conclusion', 'Interpretation considers the exact variant, inheritance, its frequency in populations, the person’s features and evidence about protein function. A variant of uncertain significance is not a confirmed diagnosis. A susceptibility variant may influence risk without being sufficient to explain disease on its own.'],
 ['The same variant can lead to different experiences', 'Penetrance describes whether a condition appears in people carrying a variant; expressivity describes how it appears. Both can vary. A relative without symptoms does not automatically settle the meaning of a result, and a shared result does not predict an identical course.'],
 ['What a confirmed result may change', 'A molecular diagnosis can support more focused counselling, assessment of relatives or consideration of disease-specific studies. It does not automatically identify an available treatment. Clinical findings and follow-up remain essential alongside the genetic explanation.']]],
 'research-progress': ['Where CVID research stands', 'Researchers are connecting antibody production, immune regulation and long-term patient experience.', [
 ['Returning to the B cell', 'A B-cell count cannot describe everything that cell can do. Researchers examine activation, antibody class switching, memory formation and plasma-cell differentiation. They also study the signals provided by T cells and the environments in which these steps occur.'],
 ['Deficiency and overactivity can coexist', 'One major question is why impaired defence against infection can accompany autoimmunity and inflammation. Studies connect cell populations, cytokines and tissue findings, looking for mechanisms that explain these combinations rather than treating them as unrelated labels.'],
 ['Looking beyond recurrent pneumonia', 'Lung research distinguishes airway damage from inflammatory tissue disease and asks how changes can be recognised and followed. A useful marker must eventually tell clinicians something meaningful about outcomes, not merely differ between groups in a study.'],
 ['The gut and its microbial environment', 'Mucosal antibodies help manage contact with microbes. Studies of IgA, microbial material and inflammatory signals explore whether altered containment contributes to immune activation. Such associations are clues, not proof that a particular dietary change or supplement treats CVID.'],
 ['Genetics and single-cell methods', 'Genetic studies can provide a more specific diagnosis for some people. Single-cell methods investigate how different immune populations use genes and communicate. Many measured cells can reveal detail, but cannot substitute for studying enough independent patients.'],
 ['From a mechanism to better care', 'Finding an altered pathway creates a question for further testing. Establishing a treatment requires evidence about benefit, harm, dose and the people for whom it is appropriate. Results in a related monogenic disease cannot simply be transferred to all CVID.'],
 ['Registries reveal changes over time', 'Long-term records help describe complications, diagnostic delays and treatment experiences. They complement laboratory research and can help plan trials. Missing information and differences between centres still matter when interpreting comparisons.'],
 ['What is established, and what remains open?', 'CVID is biologically and clinically varied. Antibody protection, immune regulation and organ health are connected. The remaining challenge is to make those connections useful for individual care without claiming more certainty than the evidence provides.']]],
 'lab-results': ['What is my immunoglobulin report telling me?', 'Antibody amounts, specific responses and B-cell measurements answer different questions.', [
 ['IgG: protection in blood and tissues', 'IgG is a major antibody class in circulation. A result describes its concentration at a particular time; it does not measure every aspect of immune protection. Age, laboratory reference ranges, treatment and the broader clinical history matter. Results during replacement therapy also reflect the antibodies that have been given.'],
 ['IgA and IgM: different roles', 'IgA is important at mucosal surfaces such as the gut and airways. A blood measurement does not directly describe every mucosal compartment. IgM often contributes early in an antibody response. These classes are not interchangeable, and one normal value does not cancel out all other findings.'],
 ['Specific antibody titres', 'A titre asks about antibodies against a particular target, rather than the total amount of an antibody class. Specialists may use response testing to investigate function in an appropriate clinical setting. Timing and prior immunoglobulin replacement can complicate interpretation, so numbers should not be judged in isolation.'],
 ['IgG subclasses and B-cell populations', 'IgG subclasses provide another layer of information, but a subclass value alone does not establish CVID. B-cell testing distinguishes populations at different stages, including switched-memory cells. Having B cells and being able to develop an effective antibody response are not the same thing.'],
 ['What the report cannot tell you alone', 'A single result does not forecast your entire disease course or determine a treatment plan. Trends, infections, organ findings and alternative causes of low antibodies all contribute to assessment. The useful question is what the test adds to your particular clinical picture.']]],
 'immunoglobulin-replacement': ['What does immunoglobulin replacement actually replace?', 'It supplies protective antibodies; it is not a general-purpose immune boost.', [
 ['Whose antibodies are these?', 'Replacement products contain immunoglobulin, mainly IgG, prepared from donated plasma and processed under controlled manufacturing conditions. They provide a range of antibodies rather than teaching your own B cells to make an entirely new immune response.'],
 ['What it can do', 'For people who need it, replacement supports protection against infections when their own antibody production is inadequate. Its effect is judged through clinical experience as well as laboratory results. Infection frequency, severity and day-to-day treatment burden all matter.'],
 ['What it cannot do', 'Replacement does not correct every cause of immune dysregulation or reliably resolve every inflammatory complication. It is also not the same as restoring normal IgA protection at every mucosal surface. Other symptoms may need their own assessment even when IgG replacement is helping.'],
 ['Intravenous and subcutaneous delivery', 'Intravenous treatment delivers immunoglobulin into a vein; subcutaneous treatment delivers it under the skin for gradual absorption. The approaches differ in schedule, practical demands and patterns of blood levels. Suitability and training depend on clinical circumstances and local services.'],
 ['Changes between doses', 'Some people notice symptoms towards the end of a treatment interval. These experiences are worth discussing, but do not by themselves prove a particular cause or justify changing a dose. Clinicians consider the pattern alongside infections, results and treatment tolerability.'],
 ['Safety is part of individual care', 'Products, routes and patient circumstances differ. The treating team should explain possible reactions and what to do if they occur. This article explains the principle of replacement; it is not an instruction to start, stop or adjust treatment.']]],
 'family': ['What should family members know?', 'Understanding, practical help and respect for independence can make a difference.', [
 ['CVID is not contagious', 'You cannot catch CVID from a family member. The diagnosis describes an immune problem, not an infection that spreads between people. Everyday support starts by separating the condition from the infections a person may experience.'],
 ['There is no single answer about inheritance', 'Some families have a defined genetic cause; many do not. Whether relatives need assessment depends on the diagnosis, family history and specialist advice. Having CVID does not automatically mean every child or sibling will have the same condition.'],
 ['Practical help can be specific', 'Support may involve listening, helping with appointments when invited, or making room for fatigue and treatment schedules. Ask what would help rather than assuming. Someone who looks well may still be managing a substantial burden, while someone with a diagnosis still needs ordinary independence and interests.'],
 ['Explaining it to children and teenagers', 'Use language appropriate to their age: parts of the immune system need extra support, and the care team helps provide it. The explanation should allow questions without making the child feel responsible for being ill. Involve young people in decisions in ways they can understand.'],
 ['Families also have feelings', 'Uncertainty can bring frustration, worry or exhaustion. Those feelings do not mean the family is failing. Honest conversation and appropriate support can help everyone adapt without allowing the diagnosis to define every part of family life.']]],
 'research-participation': ['What does joining a patient registry or research study involve?', 'Patient experiences can help research answer questions that one hospital cannot answer alone.', [
 ['One person’s experience can help many others', 'Repeated infections, lung investigations, gut symptoms, genetic findings and treatment experiences all contain questions that medicine has not fully answered. Bringing these experiences together has helped show that CVID is not only an antibody deficiency, and that its course differs between people.\nParticipation is more than contributing a number. It can help research address daily life as well as laboratory measurements. Some people mainly experience infection; others find fatigue, inflammation or the burden of treatment more difficult.'],
 ['Patient registries: a longer view of disease', 'A registry usually records diagnosis, treatment, investigations and follow-up in a structured way. It is not, by itself, a trial of a new medicine and generally does not assign a change in treatment. By combining records, researchers can investigate which problems occur together and how illness changes over time.\nSystems such as ESID and USIDNET bring together experiences across centres. What is collected, how often it is updated and who can access it depend on the particular registry. A website interest form is not the same as joining one of these formal registries.'],
 ['Scientific studies: asking why', 'Research may involve genetics, immune cells, biological samples or quality of life. A study might ask for blood, saliva or another sample, or ask about fatigue, school, work or infusion experiences. These approaches can explore mechanisms that are not visible in routine tests.\nThere may be no direct personal benefit. A sample may contribute to a molecular discovery, while a questionnaire may help researchers measure whether a treatment improves everyday life. The study information should explain exactly what participation involves.'],
 ['Clinical trials: testing an approach properly', 'Clinical trials test an intervention under a defined protocol. They ask about safety and benefit, rather than assuming that a promising mechanism will work in patients. Participants may be allocated to different groups, and some studies use a comparison treatment or placebo. The arrangements vary by study.\nA trial may examine a medicine, a dosing strategy or another intervention. Participation does not guarantee improvement. Ethics review, safety monitoring and a clear explanation of uncertainty are essential parts of responsible research.'],
 ['Participation is a partnership', 'Wanting future patients to receive answers sooner is one reason to participate, but it is not an obligation. It is also reasonable to want clearer information and to know whether research findings will be shared with you. Additional contact with a research team should not be confused with a guarantee of better care.\nPeople living with a rare disease, families, clinicians and scientists bring different knowledge to the same questions. Participation works best when those contributions are respected.'],
 ['Informed consent means an informed choice', 'Before enrolment, ask what information or samples are needed, what visits are involved, what risks and potential benefits exist, and how data will be stored and used. Ask about withdrawal and what can happen to data already analysed. These details belong in the study’s consent process, not in a general website promise.\nYou can ask questions and reconsider participation. Declining research should not affect your ordinary care. Expressing interest here is not consent to a study, does not share your records with a centre and does not determine eligibility.'],
 ['Patients should also help set the questions', 'Fatigue, recovery after infection, treatment schedules and the ability to study, work or travel can matter as much as a laboratory result. Patient involvement can help decide which outcomes studies measure and which questions deserve priority.\nYou can begin by learning about a project and its practical demands. Only the official research team can confirm whether it is open to you. Whether to contact them and whether to take part remain your decisions.']]],
};
const genes = [
 ['cd19','CD19: helping B cells hear the activation signal','A co-receptor that strengthens B-cell signalling.',[
 ['A signal amplifier, not the antigen receptor itself','The B-cell receptor recognises a target. CD19 helps strengthen the signal that follows, acting with partners including CD21 and CD81. This coordination helps a B cell respond appropriately rather than simply responding to every contact.'],
 ['From recognition to memory','Activation is an early step on a longer path to antibody production and memory. If signals are inadequate, having B cells in the blood does not guarantee that they will develop effective specific antibody responses.'],
 ['When CD19 function is impaired','Rare inherited CD19 deficiency can cause antibody deficiency despite the presence of B cells. Clinical interpretation combines antibody measurements, responses and genetic evidence. A low CD19 measurement alone is not equivalent to a confirmed inherited disorder.'],
 ['What this teaches us about CVID','CD19 provides a specific example of how a signalling problem can underlie an antibody-deficiency presentation. It does not explain all CVID. Research into this co-receptor system helps distinguish cell numbers from the quality of a response.'],
 ['Interpreting a genetic finding','The exact variant, inheritance and supporting functional evidence matter. A gene name on a report does not establish a diagnosis or indicate that a treatment targeting the same molecule would be appropriate.']]],
 ['cd81','CD81: organising the B-cell signalling platform','A membrane organiser that supports the CD19 co-receptor complex.',[
 ['Building a stable platform','CD81 belongs to the tetraspanin family of membrane proteins. Rather than recognising an antigen itself, it helps organise proteins at the cell surface and supports the normal presentation and function of CD19.'],
 ['Why a partner matters','A receptor system depends on its components being in the right place. A problem with CD81 can therefore disrupt a response even when the gene encoding CD19 itself is not the underlying cause. This illustrates why immune signalling is studied as a network.'],
 ['When CD81 is deficient','Rare inherited deficiency has been associated with impaired antibody responses. Similarities to CD19 deficiency arise from their functional partnership, but the molecular diagnoses are distinct. Patient numbers are small, so the full range of outcomes is not precisely known.'],
 ['Genetic clues and current knowledge','Clinical findings, surface-protein measurements and genetic evidence can be considered together. Research links membrane organisation with antibody responses; it does not establish that every CD81 variant causes disease or that every person with CVID has this defect.']]],
 ['cr2-cd21','CR2/CD21: recognising a target tagged by complement','CD21 connects complement recognition with B-cell activation.',[
 ['A tag that helps a target stand out','Complement proteins can attach fragments to a target. CD21 can recognise certain complement fragments, helping link the target with the B-cell co-receptor system. The tag analogy describes an immune signal, not conscious recognition by a cell.'],
 ['Working with CD19 and CD81','CD21 participates in a complex that helps strengthen B-cell signalling. Antigen recognition and complement recognition can cooperate. CD21 also has roles in antigen handling within lymphoid tissue, illustrating that the same molecule can contribute in more than one location.'],
 ['Deficiency is not the same as a low-expression population','Rare CR2 defects can impair antibody responses. However, CD21-low B cells reported on an immune phenotype are a cell population with reduced surface expression; their presence does not by itself diagnose inherited CD21 deficiency. This distinction prevents two very different findings being confused.'],
 ['What researchers can learn','Studying rare defects helps explain how complement supports adaptive immunity. Interpreting an individual result still needs the exact genetic finding and clinical evidence. Small numbers of documented cases limit confident predictions about the course of disease.']]],
 ['ms4a1-cd20','MS4A1/CD20: supporting the signals that activate a B cell','CD20 is involved in B-cell function, including calcium signalling.',[
 ['Signals also travel inside the cell','Recognition at the surface is followed by internal changes. Calcium acts as an intracellular messenger, contributing to activation. CD20 is a membrane protein involved in B-cell signalling; a simplified calcium analogy does not describe every detail of its function.'],
 ['What inherited deficiency shows','Rare MS4A1 defects have helped researchers understand how antibody responses can be impaired even when B cells are present. These unusual observations are informative about biology but cannot define the experience of all patients with antibody deficiency.'],
 ['An inherited defect and a medicine are different stories','Anti-CD20 medicines target cells expressing CD20 for particular clinical purposes. Receiving such a medicine is not the same as being born with an MS4A1 defect. The indications, timing and immune effects must be considered separately. A shared molecule name does not make the situations interchangeable.'],
 ['What remains uncertain','The complete relationship between CD20, signalling and individual clinical outcomes is still being studied. Genetic interpretation requires evidence about the particular variant. Rare cases provide clues, not reliable estimates of an individual person’s future.']]],
 ['tnfrsf13b-taci','TNFRSF13B/TACI: helping B cells mature and stay regulated','TACI connects BAFF and APRIL signals with antibody responses.',[
 ['Survival is not the only task','TACI is a receptor on B cells that responds to BAFF and APRIL. Its roles include supporting aspects of antibody differentiation and class switching. A B cell needs signals that coordinate maturation, not simply an instruction to multiply.'],
 ['Growth and restraint must be balanced','TACI biology also involves regulation of the B-cell compartment. This helps explain why an antibody-deficiency presentation can overlap with immune dysregulation. The pathway cannot be reduced to a single on/off button.'],
 ['A variant is not always the answer','Some TACI variants are found in people without disease and may act as susceptibility factors rather than a sufficient explanation by themselves. Finding a variant should therefore not automatically end the search for other causes. Its effect and inheritance need careful interpretation.'],
 ['What research contributes','Studies of signalling and patient genetics connect TACI with antibody responses and variable disease expression. They also show why risk associations and proven disease-causing defects must be separated. A laboratory pathway is not, by itself, a reason to select a treatment.']]],
 ['tnfrsf13c-baffr','TNFRSF13C/BAFF-R: helping young B cells survive','BAFF-R supports an important stage in the maturation of B cells.',[
 ['A selective survival signal','New B cells do not all remain in the circulation. BAFF binding to BAFF-R helps support the survival and maturation of peripheral B cells. This is part of a controlled system, not a goal of keeping every B cell alive indefinitely.'],
 ['Where the receptor fits','BAFF-R and TACI share a connection to BAFF but do not have identical roles. The receptor receiving a signal and the developmental stage of the cell influence what happens next. This is why similarly named pathways cannot simply be treated as the same mechanism.'],
 ['When function is reduced','Rare inherited BAFF-R deficiency can affect B-cell populations and antibody production. The presentation may resemble a broader antibody-deficiency diagnosis before the specific cause is established. Variation between reported patients makes individual prediction difficult.'],
 ['From a report to an explanation','A result needs to be assessed with the variant, inheritance and immune findings. Research has established the importance of BAFF-R in B-cell biology, while the limited number of affected people leaves questions about the full clinical spectrum.']]],
 ['icos','ICOS: helping T cells support B-cell training','ICOS contributes to the helper-cell partnership needed for effective antibody memory.',[
 ['Why B cells need a partner','In germinal centres, B cells receive support from follicular helper T cells. This partnership helps coordinate selection, antibody class switching and differentiation. Recognition of an antigen is only part of the process.'],
 ['A co-stimulatory signal','ICOS is expressed on activated T cells and interacts with its ligand on other cells. It supports the helper-cell response. It is not an antibody and does not itself recognise the pathogen in the way a B-cell receptor does.'],
 ['When the partnership is disrupted','Inherited ICOS deficiency can impair antibody production and memory responses. A defect on the T-cell side can therefore appear clinically as an antibody problem. That is an important reason to consider cooperation between cell types rather than only counting B cells.'],
 ['What a molecular diagnosis adds','A confirmed diagnosis can clarify the pathway and support specialist counselling. Variants still need evidence, and rare disorders can vary between individuals. Mechanistic knowledge does not automatically specify a universally suitable treatment.']]],
 ['il21-il21r','IL21/IL21R: a message that supports B-cell differentiation','A cytokine and its receptor link helper-cell signals with antibody production.',[
 ['The message and the receiver','IL-21 is a signalling protein produced by certain T cells, including follicular helper T cells. IL-21R is part of the receptor system that receives the message. A defect in the signal and a defect in its receiver are related but distinct molecular problems.'],
 ['Why the message matters','Together with other signals, IL-21 supports B-cell differentiation and antibody responses. Its effects depend on the surrounding signals and the type of cell. The graduation-message analogy is useful, but it is not the only instruction a B cell needs.'],
 ['More than an antibody measurement','Defects in this pathway can cause broader immune problems as well as impaired antibody production. IL-21 and IL-21R deficiencies should not be assumed to have identical clinical patterns. Their interpretation requires specialist assessment beyond a single immunoglobulin value.'],
 ['What studies establish and leave open','Rare patients and functional experiments help connect the pathway with human immune defence. Limited numbers leave uncertainty about the full spectrum. Genetic and functional evidence are needed before attributing a person’s disease to a variant.']]],
 ['nfkb1','NFKB1: turning immune signals into cellular action','NFKB1 contributes to a transcription-factor system used by several immune cells.',[
 ['From the surface to the instructions','NF-κB proteins help regulate gene activity after a cell receives signals. NFKB1 encodes a precursor called p105 and the p50 component. This is an internal regulatory system, not a single surface receptor.'],
 ['Why B cells depend on it','B-cell activation and differentiation depend on coordinated gene programmes. Impaired NFKB1 function can disturb antibody responses, helping explain why an internal signalling defect can first appear as recurrent infection and low immunoglobulins.'],
 ['Why inflammation can also occur','The pathway contributes to regulation in several immune-cell types. Its disruption can be associated with immune dysregulation as well as infection susceptibility. The balance of manifestations differs, and not everyone develops the same complications.'],
 ['One copy can matter, but expression varies','Some disease-causing NFKB1 defects act through reduced gene dosage. A person carrying such a variant may develop disease later or have a different presentation from a relative. Neither a shared variant nor a symptom-free relative gives a complete prediction.'],
 ['What research is clarifying','Patient cohorts and functional studies investigate how variants alter protein function and why disease expression varies. A confirmed defect can refine the diagnosis, but a variant of uncertain significance is not equivalent to that confirmation.']]],
 ['stat3-gof','STAT3 gain of function: when a regulatory signal becomes excessive','Excess activity in an immune pathway can coexist with impaired protection.',[
 ['A gene can work too strongly','STAT3 helps transmit signals to gene-regulatory programmes. Gain of function means a variant increases or alters activity in a disease-relevant way. It is different from STAT3 loss of function; naming the gene alone is not enough to describe the condition.'],
 ['Why overactivity can cause immune deficiency','An effective immune system depends on balanced development and regulation, not maximum activity. Excessive signalling can disturb that balance, producing autoimmunity or inflammation alongside impaired defence. More signal does not necessarily mean better protection.'],
 ['A varied clinical picture','STAT3 gain-of-function disease can involve multiple organs, growth and immune regulation. Some people have antibody deficiency, but it is a more specific disorder and should not be presented as a cause of every CVID diagnosis.'],
 ['Evidence before interpretation','The exact variant and evidence for its functional effect are essential. Research on pathway-directed approaches belongs to the defined disorder and its clinical context; it cannot automatically be applied to all people with low antibodies.']]],
 ['stat1-gof','STAT1 gain of function: when persistent signalling disrupts immune balance','The strength of one response does not describe the whole immune system.',[
 ['An important signalling pathway','STAT1 participates in responses to interferons. Gain-of-function variants can alter the strength or persistence of signalling. A continuously amplified signal can disturb other immune functions rather than providing universal protection.'],
 ['Why Candida is an important clue','Persistent or recurrent mucocutaneous Candida infection is a characteristic feature of many reported cases. It is not enough on its own to diagnose STAT1 gain-of-function disease: many other conditions can cause fungal infection.'],
 ['A wider immune pattern','Other infections, autoimmunity and variable antibody abnormalities can occur. The condition is therefore not simply a form of low IgG. Clinical assessment brings together the pattern over time rather than assigning a diagnosis from one symptom.'],
 ['What molecular studies add','Functional investigation can distinguish a disease-causing increase in activity from an uninterpreted variant. Studies of targeted treatment examine a specific pathway and patient group; a result cannot be generalised to all CVID or used to choose medicine without specialist care.']]],
 ['pik3r1','PIK3R1: regulating the immune cell’s accelerator','A regulatory component helps keep PI3K signalling appropriately controlled.',[
 ['Signalling needs a regulator','PIK3R1 encodes regulatory components of the PI3K system. This pathway helps cells respond to growth and activation signals. The accelerator analogy explains the need for balance, but different variants can have different biological effects.'],
 ['Why excessive signalling can impair immunity','Certain variants cause activated PI3K-delta syndrome type 2, or APDS2. Overactive signalling can disrupt lymphocyte maturation and function. It can therefore produce infection susceptibility despite excessive activity in one part of the system.'],
 ['More than one clinical label','Antibody deficiency may occur alongside lymphoid enlargement and other immune problems. A confirmed APDS2 diagnosis is more specific than a general antibody-deficiency label. Not every PIK3R1 variant causes APDS2, and the gene is also associated with other phenotypes.'],
 ['Research follows the defined mechanism','Pathway-directed research illustrates why a precise molecular diagnosis may matter. Whether a particular approach is appropriate depends on the established diagnosis and clinical assessment, not merely on a gene name appearing in a report.']]]
];
for (const [slug,title,excerpt,sections] of genes) records[slug]=[title,excerpt,sections];
export const englishArticles=chineseArticles.map(original=>{
 const [title,excerpt,sections]=records[original.slug];
 const sourceText=x=>x.replace('IEI 实践参数。','practice parameter for IEI.').replace(/ICON：CVID 国际共识[.。]/,'International Consensus Document (ICON): Common Variable Immunodeficiency Disorders.').replace('IEI 临床诊断工作定义。','working definitions for clinical diagnosis of IEI.');
 return {...original,title,excerpt,blocks:[{type:'paragraph',text:excerpt},...sections.flatMap(([heading,text])=>[{type:'heading',text:heading},{type:'paragraph',text}])],sources:original.sources.filter(x=>!/^\d{1,2}:\d{2}$/.test(x.trim())).map(sourceText)};
});
