// Additional patient context: distinguish explanatory background from paper findings.
export function addResearchDepth(items) {
 const additions = [
 [
 ['为什么“抗体少”和“免疫活跃”并不矛盾？','Why low antibodies and immune activation can coexist','抗体不是免疫系统的全部。它们有助于限制病原体和微生物成分的接触，而感受这些成分的细胞仍可能被激活。可以把这理解为一道防线不够严密，后面的警报系统却仍在工作，甚至持续收到刺激。因此，免疫缺陷不等于身体所有免疫反应都低下；炎症也不能简单理解为“免疫力太强”。这段背景有助于理解论文提出的联系，但并不能凭症状确定某位患者正在经历同一过程。','Antibodies are one part of immunity, not a measure of the activity of the whole system. They help limit exposure to microbes and their products. Cells that sense those products may still respond even when antibody protection is inadequate. A useful analogy is an imperfect barrier with an alarm system behind it: a gap in containment may increase the signals reaching that alarm. This explains why deficiency and activation are not logical opposites. It does not establish that this particular mechanism causes a given person’s symptoms.'],
 ['这些指标分别能说明什么？','What the measurements do—and do not—represent','类别转换记忆 B 细胞提示抗体反应经历过某些成熟过程，但不能单靠数量判断全部防御能力。16S DNA 是微生物来源线索，不告诉我们细菌是否仍然存活，也不能独自定位材料来自哪里。IFN-γ、CXCL9 与 BAFF 则反映不同的免疫信号。把它们放在一起，可以提出相互联系的假设；把某一个指标单独拿出来，却很容易把研究发现误当成已经可以用于个人诊断的检验。','Switched-memory B cells provide information about part of the history of an antibody response, rather than a complete measure of protection. Bacterial DNA is a clue to microbial material; it does not establish that living bacteria are present or identify the source by itself. Inflammatory mediators report other aspects of immune activity. Considering several measurements together can support a biological hypothesis. Turning one measurement into an individual diagnostic test would require additional evidence about reliability, interpretation and usefulness.'],
 ['从联系到干预，还差哪些证据？','What would strengthen the explanation?','要判断这条机制是否能成为治疗方向，需要更清楚地观察时间顺序：屏障变化、微生物暴露和炎症信号是否按预期先后出现？还需要在不同患者群体中重复观察，并检验改变某个环节能否改变有意义的结局，例如症状或器官炎症，而不只是改变一个血液指标。这篇论文没有完成这些治疗验证。尤其不能由“低 IgA 与炎症有关”直接推导出补 IgA、用益生菌或改变饮食就能解决问题。','Stronger causal evidence would clarify the order of events and test whether changing a proposed step changes a meaningful outcome. Repeating an association in independent groups is useful, but is still different from demonstrating a safe intervention. A future treatment study would need to examine symptoms, organ outcomes and harms—not only a blood marker. This paper does not show that IgA supplementation, probiotics or a dietary change improves CVID. Its importance is in making a possible connection testable, not in supplying a new self-treatment.']
 ],
 [
 ['“单细胞”为什么不是“只研究一个细胞”？','What single-cell analysis adds','单细胞技术把混合样本拆开，分别读取许多细胞的信息。研究人员可以比较不同成熟阶段，而不是只看一管血的平均值。不过，测到很多细胞不等于研究了很多患者：来自同一位参与者的细胞共享许多背景因素。因此，发现阶段的细胞数量和独立验证的人数回答的是不同问题，都需要注意。','Single-cell methods read many cells separately rather than averaging them together. This can reveal differences between developmental stages or small populations that would otherwise be obscured. However, thousands of measured cells are not thousands of independent patients. Cells from one person share clinical and biological context. The number of people and the number of cells therefore answer different questions about how detailed a result is and how widely it might apply.'],
 ['甲基化、开放程度和 RNA 如何互相补充？','Three views of gene regulation','可以把 DNA 甲基化理解为调控状态的一部分，把染色质开放程度理解为一段信息是否容易被细胞接触，把 RNA 理解为当时正在被读取的信息。这个比喻是简化的：甲基化不是任何位置都等于“关闭”，RNA 变化也不一定最终变成蛋白功能变化。多种读数相互支持，能使机制解释更有说服力，却仍不等于已经证明最初的致病原因。','DNA methylation describes one regulatory layer, chromatin accessibility asks which regions are physically available, and RNA records which instructions are being transcribed. These are complementary views, not interchangeable measurements. Methylation is not a universal off switch, and an RNA difference does not necessarily translate into a corresponding change in protein function. Agreement between layers can strengthen an interpretation while still leaving the original cause uncertain.'],
 ['为什么这篇较早的论文仍值得读？','Why a foundational paper remains useful','这篇论文发表于 2022 年，因此这里把它作为代表性的机制研究，而不是今天刚出现的新发现。它的重要性在于改变观察问题的角度：同样叫 B 细胞，成熟阶段和调控状态可能很不同；没有找到明确单基因原因，也不代表细胞内部没有可研究的变化。这种认识能够帮助理解后续研究，但不能把“表观遗传”解释成患者可以自行纠正的生活习惯问题。','This paper was published in 2022 and is presented as foundational work, not a newly released finding. Its value is the perspective it offers: the label “B cell” contains different stages and regulatory states. An unresolved single-gene explanation does not mean there is no biology to investigate. Equally, epigenetics should not be interpreted as proof that a patient’s habits caused the disease or that an untested lifestyle intervention can reverse it.']
 ],
 [
 ['症状重叠，为什么仍值得寻找机制？','Why mechanisms matter when symptoms overlap','不同通路可能影响同一个结果，例如抗体不足；同一条通路也可能参与几个器官的问题。用症状直接反推基因，就像只凭灯不亮来判断电路里究竟哪个零件坏了：症状指出需要排查，却未必能定位。遗传信息的价值是增加一层解释，而不是用一个基因名字取代完整的临床观察。','Different pathways can lead to a shared outcome, such as reduced antibody production, while one pathway can influence several organs. Working backwards from a symptom is therefore difficult. A symptom can identify something that needs investigation without locating the precise molecular cause. Genetics adds another layer of explanation; it does not replace the clinical history or make every complication a direct consequence of one variant.'],
 ['队列中的比例，为什么不能直接变成个人概率？','Why a cohort percentage is not a personal forecast','一家专科中心收治的人群可能有更复杂的表现，也可能更容易获得某些检测。检测范围、变异判读标准和入组方式都会影响研究中“找到遗传线索”的比例。同样重要的是，报告把什么算作遗传发现：易感变异和证据充分的致病变异并不是同一类信息。因此，讨论自己的检测时，更有用的是明确检测能回答什么，而不是期待复制一个论文百分比。','A specialist centre may see more complex cases and have different access to testing than other services. Test coverage, selection and interpretation affect the proportion with genetic findings. The definition of a finding also matters: susceptibility and a well-supported causal defect are not identical categories. A cohort percentage should not be treated as the chance that any particular reader will receive a molecular diagnosis.'],
 ['结果怎样与长期随访配合？','How genetics and follow-up complement each other','一个明确诊断可能帮助团队关注特定机制、讨论家属评估或寻找相应研究。但是症状是否出现、何时出现、影响到什么程度，仍需要实际随访。暂时没有明确遗传结果的患者，同样需要根据已经存在的表现得到照护。这篇研究支持的是把不同证据拼在一起，而不是把患者分成“有基因所以有答案”和“没基因所以没答案”两组。','A confirmed diagnosis may help focus questions about a pathway, relatives or research opportunities. Follow-up still establishes whether a complication develops and how it affects the person. Someone without a resolved genetic finding still needs care for their actual clinical problems. The useful distinction is not between people with an answer and people without one, but between what each type of evidence can currently explain and what remains uncertain.']
 ],
 [
 ['登记不是把所有经历混成一个平均数','A registry is more than one average','不同疾病、年龄和治疗背景的人不能不加区分地比较。规范的登记需要尽量统一疾病定义、记录项目和时间点，再在适当人群中提出具体问题。例如，了解诊断延迟与研究治疗结局需要不同的分析。大样本能让少见的情况被看见，但不能自动消除资料缺失和人群差异。','People with different diagnoses, ages and treatment histories cannot simply be treated as interchangeable. A useful registry needs consistent definitions, records and timing, followed by an analysis suited to the question. Studying diagnostic delay is different from comparing outcomes after treatment. Large numbers help reveal uncommon experiences, but do not automatically remove missing data or differences between populations.'],
 ['为什么登记不等于试药？','Why a registry is different from a treatment trial','登记通常记录已经发生的诊疗与随访，而临床试验会按照研究方案分配某种干预。两者的目的、额外负担和风险可能不同。一项登记发现可以提示值得开展试验的问题，却不能仅凭记录中某组结局更好，就认定那项治疗一定造成改善。医生选择治疗时本来就会考虑病情，这也会影响结果比较。','A registry commonly records care and follow-up, whereas a clinical trial assigns an intervention under a protocol. Their commitments and risks can differ. Registry observations may identify questions for a trial without proving why one group did better. Treatment choices already depend on illness severity and other characteristics, which can influence later comparisons. This is why observational evidence and intervention testing complement each other.'],
 ['在这个网站表达兴趣，和正式登记有什么区别？','Interest here is not formal enrolment','在网站选择关注方向，只能表达你想进一步了解什么。正式患者登记由具体项目负责，需要说明资料用途、授权范围、退出方式以及适用的伦理和隐私安排。读到一篇登记论文，不代表作者正在通过本站招募；填写演示表单也不会进入 ESID 或其他登记系统。你可以先访问项目官方信息，再决定是否询问研究团队。','Selecting an interest on this website is not enrolment in ESID or another registry. Formal participation is handled by the project and requires its own information and consent process. Reading a report does not mean its authors are recruiting through this site, and our demonstration form does not send information to them. The next step, if you wish, is to read the project’s official information and ask its team about participation.']
 ]
 ];
 additions.forEach((sections,index)=>items[index].sections.push(...sections));
 items.push({
 date:'2023-05-08',type:['系统综述','Systematic review'],sample:['58 项研究；共描述 796 名患者','58 studies describing 796 patients'],
 title:['肺部检查各在寻找什么？读懂 CVID 间质性肺病的研究','What are lung tests looking for? Understanding research on CVID-related lung disease'],
 paper:'Diagnostic testing for interstitial lung disease in common variable immunodeficiency: a systematic review',
 source:'https://www.frontiersin.org/journals/immunology/articles/10.3389/fimmu.2023.1190235/full',
 intro:['CT、肺功能、灌洗和活检不是重复检查。研究梳理了不同检查提供的线索，以及现有证据为何还不能给出适用于所有人的单一方案。','Scans, lung function, lavage and biopsy answer different questions. This review examines the evidence and why it does not yield one universal testing plan.'],
 sections:[
 ['为什么不能把肺部问题都看成感染？','Why infection is not the only question','CVID 患者的肺部问题可能来自反复感染造成的气道损伤，也可能涉及肺组织炎症。有些人在不同时间会面对不止一种问题。呼吸困难、咳嗽或影像异常本身不能把这些情况完全区分开。这篇研究聚焦 CVID 相关间质性肺病的诊断检查，而不是所有肺部并发症，也不是比较哪种药最好。','People with CVID can have airway damage associated with infection, inflammation involving lung tissue, or more than one process. Symptoms and abnormal imaging do not independently identify the cause. This review addresses investigations for CVID-related interstitial lung disease. It is not a review of every respiratory complication and does not compare which medicine works best.'],
 ['研究如何整理已有证据？','How the evidence was assembled','作者汇集 58 项研究，共描述 796 名患者。这里的数字是已发表研究中的患者总数，不是一项新开展的、统一安排所有检查的试验。纳入资料的研究设计和检查选择并不一致，这会限制直接比较。综述能展示临床研究实际使用了哪些方法，也能指出证据仍薄弱的地方。','The authors assembled 58 studies describing 796 patients. This is a collection of published evidence, not one new experiment in which every participant received the same tests. Differences in study design and investigation choices limit direct comparison. A review can show how methods have been used and identify gaps without establishing a universally best sequence.'],
 ['影像与肺功能，分别看结构和功能','Structure and function are different views','高分辨率 CT 提供肺部结构变化的信息，帮助发现异常分布；肺功能检查则从另一角度描述呼吸系统的工作情况。两者不是互相替代的“同一种答案”。结构改变与功能影响未必在同一个时间、以同样幅度出现。因此，单次结果需要结合既往情况和临床表现理解，而不是在网页上套用一个阈值自行判断。','Imaging describes structural patterns; lung-function measurements describe aspects of how the respiratory system works. They are not duplicate answers. Structural and functional changes do not necessarily appear at the same time or move in parallel. Their meaning depends on the person’s history and clinical context. This explanatory distinction is not a recommendation that every reader needs every test.'],
 ['灌洗和组织取样回答更具体的问题','Sampling asks more specific questions','综述中，支气管肺泡灌洗常用于帮助排查感染；肺活检能够提供组织层面的信息。但能取得更多组织信息，不等于每个人都需要活检。取样方式、能够回答的问题和操作负担不同，需要由临床团队权衡。不能把论文中“有多少项研究使用了活检”，误读为“有多少患者应该做活检”。','In the review, bronchoalveolar lavage was commonly used to help exclude infection, while biopsy provided tissue information. More tissue information does not imply that everyone needs a biopsy. Methods differ in what they can answer and in their burdens and risks. The proportion of publications reporting a procedure is not the proportion of patients who should undergo it.'],
 ['这些结果为什么还不能成为统一检查清单？','Why this is not a universal checklist','许多资料来自观察性研究、小系列或病例报告，不同团队使用的定义和检查组合也有差异。如果某种检查主要用于病情较复杂的人群，其结果就不能直接与另一种人群相比。综述揭示的是证据的组成与不足，而不是用一个排名替代多学科判断。它发表于 2023 年，阅读时还应注意后续证据可能更新。','Much of the evidence comes from observational work and small reports with differing definitions and investigation pathways. A test used mainly in complex cases cannot be fairly compared with another used in a different population without accounting for that difference. Published in 2023, this review provides context for understanding the evidence rather than a current personalised testing checklist.'],
 ['患者可以怎样理解这一组检查？','What a patient can take from this','最有帮助的认识是：医生可能在同时回答几个问题——有没有感染、结构哪里改变、功能受到多少影响，以及是否需要组织证据。你可以询问某项检查主要想澄清什么，它的结果会怎样影响下一步安排。具体是否进行检查，应由了解你情况的团队决定。把不同证据放在一起，比把任何一个结果当成全部答案更接近这篇研究的意义。','The useful takeaway is that a team may be asking several questions: whether infection is present, where tissue has changed, how function is affected and whether tissue evidence is needed. Asking what an investigation is intended to clarify can make the process easier to understand. Whether to perform it remains an individual clinical decision. The point is to combine complementary evidence rather than make one result carry the whole diagnosis.']
 ]});
}
