import { renderCentreEvidence } from './centre-evidence.js';
import { chineseArticles } from './content-zh.js';
import { englishArticles } from './content-en.js';
import { localiseDisplay } from './locale-text.js';
import { translatedCentrePapers } from './centre-papers-zh.js';
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pubmed = 'https://pubmed.ncbi.nlm.nih.gov/';
const curated = [
  {match:'上海儿童医学中心',intro:'Teams at Shanghai Children’s Medical Center have published on genetic diagnosis and treatment of childhood inborn errors of immunity, including Wiskott–Aldrich syndrome. These are disease-specific IEI studies, not evidence that the same investigations or treatments apply to every person with CVID.',papers:[['37011982','Therapeutic efficacy of hematopoietic stem cell transplantation for Wiskott-Aldrich syndrome in 60 children','2023','Retrospective cohort · 60 children','Reports transplant outcomes in children with Wiskott–Aldrich syndrome. This is not a study of routine CVID treatment.'],['31354712','When WAS Gene Diagnosis Is Needed: Seeking Clues Through Comparison Between Patients With Wiskott-Aldrich Syndrome and Idiopathic Thrombocytopenic Purpura','2019','Retrospective diagnostic comparison','Examines clinical clues for investigating WAS. Such clues support specialist assessment; they do not diagnose an individual patient.']]},
  {match:'复旦大学附属儿科',intro:'The clinical immunology team has published work on early genetic diagnosis, infection patterns and molecular causes of childhood inborn errors of immunity. These studies cover broader IEI populations, not only CVID.',papers:[['32431812','Screening for primary immunodeficiency diseases by next-generation sequencing in early life','2020','Single-centre infant study','Examines early genetic diagnosis in infants with infection or abnormal blood counts. Infant IEI findings cannot be generalised to adult CVID.'],['36662455','Clinical and Genetic Characteristics of BCG Disease in Chinese Children: a Retrospective Study','2023','Retrospective study','Examines clinical and genetic patterns in children with BCG disease; this is broader IEI research.'],['38922539','Novel Mutation in the Moesin (MSN) Gene Leads to Immunodeficiency with Epstein-Barr Virus (EBV) Infection and Dermatomyositis-Like Symptoms','2024','Molecular case report','Describes a rare MSN-associated immune disorder. A case report cannot establish a general treatment effect.']]},
  {match:'重庆医科大学',intro:'This paediatric rheumatology and immunology team has published clinical and molecular studies of primary immunodeficiency, including antibody deficiencies, as well as research on complications and genetic approaches.',papers:[['23673420','Distribution, clinical features and molecular analysis of primary immunodeficiency diseases in Chinese children: a single-center study from 2005 to 2011','2013','Single-centre cohort','Describes a range of childhood primary immunodeficiencies, including antibody deficiencies; it is not a CVID-only cohort.'],['41054950','Current status of BCG and OPV vaccination in children with primary immunodeficiency in Chongqing, China','2025','Observational study','Investigates vaccination history in 26 children with PID. The small, mixed cohort limits generalisation.'],['34266535','Gene editing for the treatment of primary immunodeficiency disease','2021','Review','Summarises gene-editing research; it is not evidence of an available clinical treatment at this hospital.']]}
];
const sources = `<a href="https://primaryimmune.org/understanding-primary-immunodeficiency/types-of-pi/common-variable-immune-deficiency-cvid" target="_blank" rel="noopener">IDF patient handbook ↗</a> · <a href="https://iuis.org/committees/iei/" target="_blank" rel="noopener">IUIS classification ↗</a>`;
export function installDetailPages(app, getLanguage, centres, genes, setLanguage) {
  const dialog=document.createElement('dialog'); dialog.className='detail-page'; document.body.append(dialog);
  let returnFocus;
  const zh=()=>getLanguage()==='zh';
  const articleBySlug={get:slug=>(zh()?chineseArticles:englishArticles).find(article=>article.slug===slug)};
  const topicRoutes=['infection','multi-organ','genetics','lab-results'];
  const geneRoutes={CD19:'cd19',CD81:'cd81','CR2 / CD21':'cr2-cd21','MS4A1 / CD20':'ms4a1-cd20','TNFRSF13B / TACI':'tnfrsf13b-taci','TNFRSF13C / BAFF-R':'tnfrsf13c-baffr',ICOS:'icos','IL21 / IL21R':'il21-il21r',NFKB1:'nfkb1','STAT3 GOF':'stat3-gof','STAT1 GOF':'stat1-gof',PIK3R1:'pik3r1'};
  function open(title,body){returnFocus=document.activeElement;dialog.innerHTML=`<header><span>${zh()?'内容详情':'Explore in detail'}</span><button type="button" data-close-detail aria-label="${zh()?'关闭详情':'Close details'}">×</button></header><div class="detail-content"><h2 id="detail-title">${esc(title)}</h2>${body}</div>`;dialog.setAttribute('aria-labelledby','detail-title');dialog.showModal();dialog.scrollTop=0;}
  dialog.addEventListener('click',e=>{if(e.target.closest('[data-close-detail]')||e.target===dialog)dialog.close();if(e.target.closest('a[href^="#"]'))dialog.close();});
  dialog.addEventListener('close',()=>{if(returnFocus?.isConnected)returnFocus.focus();});
  function centreContent(index){const original=centres[index];if(!original)return null;const c={...original,source:careProfiles[index]?.source||original.source};const evidenceIndex=curated.findIndex(x=>c.name.includes(x.match));const evidence=translatedCentrePapers(curated[evidenceIndex],evidenceIndex,zh());const query=`"${c.name.split(' · ')[0]}"[Affiliation] AND (immunodeficiency OR CVID)`;const body=`${careIntro(index,c,zh())}<p class="detail-meta">${esc(c.country)} · ${esc(c.city)} · ${esc(c.service)} · ${esc(c.scope)}</p><section class="centre-summary" id="centre-about"><h2>${zh()?'中心介绍':'About this organisation'}</h2><p>${esc(evidence?.intro || (zh()?`本目录收录的${localiseDisplay(c.city,!zh())}机构。以下内容依据机构官网、研究者档案与论文署名整理；具体接诊范围、转诊要求及研究参与途径仍需向机构确认。`:`An organisation listed in our ${localiseDisplay(c.city,!zh())} directory. This profile uses official pages, investigator profiles and publication affiliations; current services, referral requirements and research participation routes still require confirmation with the institution.`))}</p><dl><dt>${zh()?'研究网络':'Research network'}</dt><dd>${esc(c.network)}</dd><dt>${zh()?'资料状态':'Profile status'}</dt><dd>${zh()?'按字段标注来源；接诊政策见上方说明':'Sources are documented by field; see care details above'}</dd><dt>${zh()?'最近目录核验':'Last directory review'}</dt><dd>${esc(c.date)}</dd></dl></section>${renderCentreEvidence(c,zh())}<section class="centre-publications"><h2>${zh()?'精选论文与患者解读':'Selected papers with patient context'}</h2><p>${zh()?'以下论文已核对机构署名。广义 IEI 研究不等于 CVID 专项成果；单篇论文也不能决定个人诊疗。':'Institutional affiliations have been checked. Broader IEI research is not CVID-specific evidence, and one paper cannot decide personal care.'}</p>${evidence?evidence.papers.map(([id,title,year,type,note])=>`<article class="detail-paper"><small>${year} · ${esc(type)} · PMID ${id}</small><h3>${esc(title)}</h3><p>${esc(note)}</p><a href="${pubmed}${id}/" target="_blank" rel="noopener">${zh()?'查看摘要与机构署名':'Read abstract and author affiliations'} ↗</a></article>`).join(''):`<p class="detail-pending">${zh()?'该机构的精选论文仍在逐篇核验。资料不足时不展示未经确认的成果归属。':'Selected papers are still undergoing article-level affiliation checks; unverified attribution is not displayed.'}</p>`}</section><section class="centre-sources"><h2>${zh()?'官方来源':'Official sources'}</h2><a class="detail-source" href="${esc(c.source)}" target="_blank" rel="noopener">${zh()?'打开机构官方页面':'Open the official institution page'} ↗</a><p><a href="${pubmed}?term=${encodeURIComponent(query)}" target="_blank" rel="noopener">${zh()?'按机构署名查找更多论文（未经逐篇核验）':'Search publications by affiliation (not individually reviewed here)'} ↗</a></p></section>`;return {c,body};}
  app.addEventListener('click',event=>{const button=event.target.closest('[data-centre-scroll]');if(button)document.getElementById(button.dataset.centreScroll)?.scrollIntoView({behavior:'smooth'});});
  function centrePage(index){location.hash=`centre-${index}`;}
  function renderCentreRoute(){const match=location.hash.match(/^#centre-(\d+)$/);if(!match)return;const page=centreContent(Number(match[1]));if(!page){location.hash='centres';return;}const {c,body}=page;app.innerHTML=`<header class="centre-page-header"><a class="brand" href="#home"><span>C</span><strong>CVID Compass</strong></a><nav aria-label="${zh()?'中心详情导航':'Centre profile navigation'}"><a href="#centres">${zh()?'← 返回中心目录':'← Back to centres'}</a><a href="#research">${zh()?'研究进展':'Research'}</a><a href="#matching">${zh()?'相关中心与研究':'Related centres & studies'}</a></nav><button type="button" class="language-toggle" data-centre-language>${zh()?'EN':'中文'}</button></header><main class="centre-page"><div class="centre-page-breadcrumb"><a href="#centres">${zh()?'医学中心与研究网络':'Centres & networks'}</a><span>/</span><span>${esc(c.city)}</span></div><div class="centre-page-hero"><p class="eyebrow">${zh()?'机构研究档案':'INSTITUTION RESEARCH PROFILE'}</p><h1>${esc(c.name)}</h1><p>${esc(c.country)} · ${esc(c.city)} · ${esc(c.service)} · ${esc(c.scope)}</p></div><div class="centre-page-layout"><article class="centre-page-content">${body}</article><aside><div class="centre-page-index"><strong>${zh()?'本页内容':'On this page'}</strong><button type="button" data-centre-scroll="centre-care">${zh()?'就医与转诊':'Care and referrals'}</button><button type="button" data-centre-scroll="centre-about">${zh()?'中心介绍':'About'}</button><span>${zh()?'PI 与团队':'PIs & teams'}</span><span>${zh()?'疾病方向':'Conditions'}</span><span>${zh()?'研究成果':'Research outputs'}</span><span>${zh()?'论文与来源':'Papers & sources'}</span></div></aside></div></main>`;app.querySelector('[data-centre-language]')?.addEventListener('click',()=>{setLanguage?.(zh()?'en':'zh');renderCentreRoute();});window.scrollTo(0,0);}
  function topicPage(index){location.hash=`article-${topicRoutes[index]}`;}
  function articleCards(slugs){return slugs.map(slug=>{const article=articleBySlug.get(slug);return `<a class="article-card" href="#article-${slug}"><span>${zh()?(article.category==='gene'?'分子科普':'CVID 科普'):(article.category==='gene'?'Immune molecules':'Understand CVID')}</span><h3>${esc(article.title)}</h3><p>${esc(article.excerpt)}</p><b>${zh()?'阅读全文':'Read article'} →</b></a>`;}).join('');}
  function renderArticleRouteV2(){
    const match=location.hash.match(/^#article-([a-z0-9-]+)$/);
    if(!match)return;
    const article=articleBySlug.get(match[1]);
    if(!article){location.hash='overview';return;}
    const isParticipation=article.slug==='research-participation';
    const back=isParticipation?'home':(article.category==='gene'?'molecules':article.category==='research'?'research':'overview');
    const contentBlocks=article.blocks[0]?.type==='paragraph'?article.blocks.slice(1):article.blocks;
    let section=0;
    const figures={
      'multi-organ':['immune-organs-v2.png',/免疫|immun/i,'抗体防御不足与免疫调节失衡是两条可重叠的路径。感染可能损伤气道；炎症及自身免疫也可影响组织。天平仅代表调节失衡，并非两类 T 细胞的数量比较。','Reduced antibody protection and immune dysregulation can overlap. Infections may damage airways, while inflammation and autoimmunity can affect tissues. The balance is a metaphor, not a comparison of two T-cell counts.'],
      genetics:['gene-protein-function-v2.png',/基因|gene/i,'以确认的 BAFF-R 缺陷为例：某些致病变异影响 B 细胞存活信号和成熟。这不是所有 CVID 的共同病因，遗传结果需结合具体变异与临床证据解释。','Confirmed BAFF-R deficiency illustrates how disease-causing variants can impair B-cell survival and maturation. It is not a universal cause of CVID; interpretation depends on the variant and clinical evidence.'],
      infection:['plasma-antibodies-v2.png',/浆细胞|Plasma cells/i,'以依赖 T 细胞帮助的应答为例：B 细胞识别抗原后激活、增殖和成熟，产生分泌抗体的浆细胞及参与再次应答的记忆 B 细胞。','A simplified T-cell-dependent response: B cells recognise antigen, activate, expand and mature, generating antibody-secreting plasma cells and memory B cells for later responses.'],
      'tnfrsf13b-taci':['receptor-signal-v2.png',/TACI/,'BAFF/APRIL 与 TACI 结合后，可通过包括 MyD88 在内的胞内信号支持抗体类别转换；这一过程需要其他信号配合。图示不是分子真实结构。','BAFF/APRIL binding to TACI can support antibody class switching through intracellular signals including MyD88, together with other signals. Shapes are schematic, not molecular structures.'],
      'immunoglobulin-replacement':['immunoglobulin-replacement-v2.png',/IgG|免疫球蛋白|antibod/i,'补充的 IgG 支持抗感染防御，但不会直接修复 B 细胞成熟或所有免疫调节环节。','Replacement IgG supports infection defence but does not directly repair B-cell maturation or every immune-regulatory pathway.'],
      'research-participation':['patient-registry-v2.png',/登记|registr/i,'在知情同意下长期记录感染、治疗和器官健康，可帮助描述病程与规划研究；观察到的关联不等于治疗因果关系。','With informed consent, longitudinal records of infections, treatment and organ health help describe disease patterns and plan research. Associations do not establish treatment causation.']
    };
    const figure=figures[article.slug];
    const figureAfter=figure?contentBlocks.findIndex(block=>block.type!=='heading'&&figure[1].test(block.text)):-1;
    const figureHtml=figure?`<figure class="science-figure"><img src="./assets/${figure[0]}" alt="${esc(figure[3])}" width="1536" height="1024" loading="lazy"><figcaption>${esc(zh()?figure[2]:figure[3])}</figcaption></figure>`:'';
    const body=contentBlocks.map((block,blockIndex)=>{
      if(block.type==='heading'){
        section+=1;
        return `<h2 id="article-section-${section}">${esc(block.text)}</h2>`;
      }
      return `<p>${esc(block.text).replaceAll('\n','<br>')}</p>`+(blockIndex===figureAfter?figureHtml:'');
    }).join('');
    const index=contentBlocks.filter(block=>block.type==='heading').map((block,i)=>`<button type="button" data-article-scroll="article-section-${i+1}">${esc(block.text)}</button>`).join('');
    const related=article.slug==='genetics'
      ? Object.values(geneRoutes)
      : article.category==='gene'
      ? ['cd19','tnfrsf13b-taci','nfkb1','pik3r1'].filter(slug=>slug!==article.slug)
      : ['infection','multi-organ','genetics','research-progress'].filter(slug=>slug!==article.slug).slice(0,3);
    const backLabel=zh()?(isParticipation?'返回首页':article.category==='gene'?'返回分子目录':back==='research'?'返回研究页面':'返回 CVID 页面'):(isParticipation?'Back to home':article.category==='gene'?'Back to molecules':back==='research'?'Back to research':'Back to Understand CVID');
    const crumbLabel=zh()?(isParticipation?'参与登记与研究':back==='research'?'研究进展':'了解 CVID'):(isParticipation?'Join registries & research':back==='research'?'Research & discoveries':'Understand CVID');
    const typeLabel=zh()?(isParticipation?'参与登记与研究':article.category==='gene'?'分子科普':'患者科普'):(isParticipation?'Join registries & research':article.category==='gene'?'Immune molecules':'Patient information');
    app.innerHTML=`<header class="centre-page-header"><a class="brand" href="#home"><span>C</span><strong>CVID Compass</strong></a><nav aria-label="${zh()?'文章导航':'Article navigation'}"><a href="#${back}">← ${backLabel}</a><a href="#centres">${zh()?'医学中心':'Find specialist care'}</a><a href="#matching">${zh()?'相关中心与研究':'Related centres & studies'}</a></nav><button type="button" class="language-toggle" data-article-language>${zh()?'EN':'中文'}</button></header><main class="article-page"><div class="article-breadcrumb"><a href="#${back}">${crumbLabel}</a><span>/</span><span>${typeLabel}</span></div><header class="article-hero"><p class="eyebrow">${typeLabel}</p><h1>${esc(article.title)}</h1><p>${esc(article.excerpt)}</p></header><div class="article-layout"><article class="article-body">${body}<section class="article-sources"><p class="eyebrow">${zh()?'参考来源':'Sources'}</p><h2>${zh()?'本文依据的资料':'References for this article'}</h2><ol>${article.sources.map(source=>`<li>${esc(source)}</li>`).join('')}</ol><p>${zh()?'本文用于帮助理解疾病和准备就医问题，不能替代免疫专科团队的评估。':'This article supports understanding and conversations with your team; it does not replace specialist assessment.'}</p></section></article><aside><div class="article-index"><strong>${zh()?'本文内容':'On this page'}</strong>${index}</div></aside></div><section class="article-related"><div><p class="eyebrow">${zh()?'继续了解':'Continue exploring'}</p><h2>${zh()?(article.slug==='genetics'?'免疫分子科普 · 12 篇':article.category==='gene'?'其他免疫分子':'相关内容'):(article.slug==='genetics'?'12 immune molecules':article.category==='gene'?'Other immune molecules':'Related reading')}</h2></div><div class="article-card-grid">${articleCards(related)}</div></section></main>`;
    app.querySelector('[data-article-language]')?.addEventListener('click',()=>{setLanguage?.(zh()?'en':'zh');renderArticleRouteV2();});
    app.querySelectorAll('[data-article-scroll]').forEach(button=>button.addEventListener('click',()=>document.querySelector(`#${button.dataset.articleScroll}`)?.scrollIntoView({behavior:'smooth',block:'start'})));
    window.scrollTo(0,0);
  }
  function wire(){
    app.querySelectorAll('.topic-grid article:not([data-detail-ready])').forEach((card,index)=>{card.dataset.detailReady='true';card.dataset.topicDetail=index;const title=card.querySelector('h3');const button=document.createElement('button');button.className='detail-title-button';button.type='button';button.textContent=title.textContent;title.replaceChildren(button);card.insertAdjacentHTML('beforeend',`<span class="detail-hint">${zh()?'阅读全文':'Read more'} →</span>`);});
    if(zh()) app.querySelectorAll('.gene-catalogue article:not([data-article-ready])').forEach(card=>{const gene=card.querySelector('h3')?.textContent?.trim();const slug=geneRoutes[gene];if(!slug)return;card.dataset.articleReady='true';card.tabIndex=0;card.setAttribute('role','link');card.dataset.articleSlug=slug;card.insertAdjacentHTML('beforeend','<b class="detail-hint">阅读分子科普 →</b>');});
    const wordingWalker=document.createTreeWalker(app,NodeFilter.SHOW_TEXT);const wordingNodes=[];while(wordingWalker.nextNode())wordingNodes.push(wordingWalker.currentNode);wordingNodes.forEach(node=>{if(!node.nodeValue.includes('CVID-like'))return;node.nodeValue=zh()?node.nodeValue.replaceAll('遗传线索与 CVID-like 疾病','遗传线索与单基因免疫缺陷').replaceAll('CVID-like 单基因疾病或其他 IEI','更具体的单基因免疫缺陷或其他 IEI').replaceAll('可形成CVID-like抗体缺陷','可表现为抗体缺陷'):node.nodeValue.replaceAll('Genetics and CVID-like conditions','Genetics and monogenic immune conditions').replaceAll('CVID-like monogenic condition or other IEI','Monogenic immune condition or other IEI').replaceAll('produce CVID-like deficiency','produce an antibody-deficiency phenotype').replaceAll('CVID-like','monogenic immune');});
    const overview=app.querySelector('.overview-page')||app.querySelector('.topic-grid')?.closest('main');
    if(zh()&&overview&&!overview.querySelector('.practical-library')){const html=`<section class="article-library practical-library"><div class="direction-title"><p class="eyebrow">治疗与家人</p><h2>把专业名词放回真实生活。</h2><p>了解免疫球蛋白替代治疗补充了什么，以及家人最需要知道的事。</p></div><div class="article-card-grid feature">${articleCards(['immunoglobulin-replacement','family'])}</div></section>`;const sourceRail=overview.querySelector('.source-rail');sourceRail?sourceRail.insertAdjacentHTML('beforebegin',html):overview.insertAdjacentHTML('beforeend',html);}
    const research=app.querySelector('.research-page');
    // The research landing page intentionally stays concise. Individual molecule articles remain reachable from their own links and article pages.
    app.querySelectorAll('.centre-card:not([data-detail-ready]),.centre-result:not([data-detail-ready])').forEach(card=>{const h=card.querySelector('h3');const index=centres.findIndex(c=>c.name===h?.textContent);if(index<0)return;card.dataset.detailReady='true';card.dataset.centreDetail=index;const button=document.createElement('button');button.type='button';button.className='detail-title-button';button.textContent=h.textContent;h.replaceChildren(button);card.querySelectorAll('.centre-fields a,.official-trial').forEach(link=>{const b=document.createElement('button');b.type='button';b.className='detail-open';b.textContent=zh()?'中心介绍、论文与官方链接 →':'Centre profile, papers & official links →';link.replaceWith(b);});});
  }
  app.addEventListener('click',e=>{const gene=e.target.closest('[data-article-slug]');if(gene){location.hash=`article-${gene.dataset.articleSlug}`;return;}const card=e.target.closest('[data-centre-detail],[data-topic-detail]');if(!card||e.target.closest('a,[data-follow-centre]'))return;if(card.dataset.centreDetail!==undefined)centrePage(Number(card.dataset.centreDetail));else topicPage(Number(card.dataset.topicDetail));});
  app.addEventListener('keydown',e=>{const gene=e.target.closest('[data-article-slug]');if(gene&&(e.key==='Enter'||e.key===' ')){e.preventDefault();location.hash=`article-${gene.dataset.articleSlug}`;}});
  function renderStandaloneRoute(){renderCentreRoute();renderArticleRouteV2();}
  window.addEventListener('hashchange',renderStandaloneRoute);
  new MutationObserver(wire).observe(app,{childList:true,subtree:true});wire();renderStandaloneRoute();
}
import { careIntro, careProfiles } from './care-profiles.js';
