import { englishArticles } from '../education/src/content-en.js';
import { chineseArticles } from '../education/src/content-zh.js';
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const figures={'infection':'plasma-antibodies-v2.png','multi-organ':'immune-organs-v2.png','genetics':'gene-protein-function-v2.png','tnfrsf13b-taci':'receptor-signal-v2.png','immunoglobulin-replacement':'immunoglobulin-replacement-v2.png','research-participation':'patient-registry-v2.png'};
export function educationView(lang,slug){
 const zh=lang==='zh', articles=zh?chineseArticles:englishArticles;
 const cards=items=>items.map(a=>`<a class="panel reading-card" href="#article-${a.slug}"><small>${a.category==='gene'?(zh?'免疫分子':'Immune molecules'):'CVID'}</small><h2>${esc(a.title)}</h2><p>${esc(a.excerpt)}</p><span>${zh?'阅读全文':'Read article'} →</span></a>`).join('');
 const groups=[['basics','Start with CVID','从了解 CVID 开始',['infection','multi-organ','lab-results']],['genetics','Genetics & immune molecules','遗传与免疫分子',['genetics',...articles.filter(a=>a.category==='gene').map(a=>a.slug)]],['living','Treatment & family life','治疗与家庭生活',['immunoglobulin-replacement','family']],['research','Understanding research','了解研究',['research-progress','research-participation']]];
 if(!slug || slug.startsWith('topic/')){const group=groups.find(g=>slug==='topic/'+g[0]);return `<section class="page-shell education-library"><a href="#cvid">← ${zh?'了解 CVID':'Understand CVID'}</a><h1>${group?(zh?group[2]:group[1]):(zh?'从哪里开始了解？':'Where would you like to begin?')}</h1><div class="angle-grid learning-groups">${group?cards(articles.filter(a=>group[3].includes(a.slug))):groups.map(([id,en,cn,slugs])=>`<a class="panel reading-card" href="#cvid/topic/${id}"><h2>${zh?cn:en}</h2><p>${zh?'按主题逐步阅读':'Explore this topic step by step'} · ${slugs.length} ${zh?'篇文章':'articles'}</p><span>→</span></a>`).join('')}</div></section>`;}
 const article=articles.find(a=>a.slug===slug);
 if(!article)return `<section class="page-shell"><a href="#cvid">${zh?'返回科普目录':'Return to the learning hub'}</a></section>`;
 return `<section class="page-shell education-article"><a class="back-link" href="#cvid">← ${zh?'了解 CVID':'Learn about CVID'}</a><h1>${esc(article.title)}</h1><p class="article-lead">${esc(article.excerpt)}</p><article>${article.blocks.map((b,i)=>b.type==='heading'?`<h2 id="reading-${i}">${esc(b.text)}</h2>`:`<p>${esc(b.text).replaceAll('\n','<br>')}</p>`).join('')}${figures[slug]?`<figure><img src="education/assets/${figures[slug]}" alt="${esc(article.title)}" loading="lazy"></figure>`:''}<h2>${zh?'参考资料':'References'}</h2><ol>${article.sources.map(s=>`<li>${esc(s)}</li>`).join('')}</ol></article><h2>${zh?'继续阅读':'Continue reading'}</h2><div class="angle-grid">${cards(articles.filter(a=>a.slug!==slug&&a.category===article.category))}</div></section>`;
}
