// English explanations of the original Chinese sections, not one-line summaries.
export function completeEnglishExplainers(items){
 const paragraphs=[
 [
 'Immunoglobulin replacement helps many people have fewer infections, yet some continue to experience gut, lung or autoimmune problems. Researchers therefore ask whether inflammation can be connected to the gap in antibody protection, rather than being an entirely separate issue. This paper examines that possible connection. It does not suggest that every continuing symptom has the same cause, or that infection prevention is unimportant.',
 'IgA is an important part of mucosal defence. Think of the gut as an interface that must absorb nutrients while managing constant microbial contact. The proposed explanation is that inadequate IgA and impaired containment may increase exposure to microbial material, sustaining immune stimulation. Bacterial DNA in a blood sample is not equivalent to an infection of the bloodstream by living bacteria. That distinction matters when interpreting the study.',
 'The team compared blood samples from people with CVID and healthy controls, examining IgA, switched-memory B cells, bacterial 16S DNA and signals including IFN-γ, CXCL9 and BAFF. These measurements concern different parts of the proposed mechanism: antibody memory, microbial exposure and immune activation. Not every participant contributed to every analysis. The total cohort size should therefore not be treated as the sample size for each individual result.',
 'Lower IgA and fewer switched-memory B cells were associated with measures of bacterial material or inflammatory activity. The authors propose a connection between reduced mucosal defence, microbial exposure and signals such as IFN-γ and BAFF. BAFF supports B-cell survival, but the balance of such signals also matters for immune regulation. This is a framework supported by the study, not a fixed sequence demonstrated in every person with CVID.',
 'The paper raises questions about whether improving mucosal defence could eventually help, but it did not test whether replacing IgA safely improves CVID outcomes. Associations do not establish the complete order of events or prove that one finding causes another. Its contribution is a more concrete hypothesis for further experiments and clinical investigation, rather than an intervention that a patient can now be expected to try.'
 ],
 [
 'The starting point was a pair of identical twins, one with CVID and the other without it. A closely shared inherited background helps researchers focus on another question: might the way cells use genetic information contribute to their different immune function? This is a valuable design for finding mechanisms. It is not a basis for assuming that one pair represents the biological diversity of everyone with CVID.',
 'DNA contains instructions, but a cell does not use every instruction at once. DNA methylation, the accessibility of chromatin and transcription help describe how information is regulated at a particular stage. Investigating these layers is different from identifying a disease-causing mutation. It also does not imply that a patient caused their illness through lifestyle or that changing a habit would reverse the regulatory differences.',
 'Blood contains a mixture of immune cells, so averaging them together can hide changes in a smaller population. The researchers combined single-cell measurements of DNA methylation, chromatin and RNA. They separated naïve and memory B-cell populations and examined responses after activation. This provided several views of maturation and communication rather than relying only on the overall number of B cells present.',
 'The findings were particularly prominent in memory B cells. Regulatory changes expected during maturation were altered, alongside differences in gene expression and communication after activation. Additional patient and control analyses supported selected findings. The work suggests that the problem can involve completing a developmental programme and cooperating with other cells, rather than simply having too few cells in the blood.',
 'The study gives biological substance to the idea that an unresolved single-gene diagnosis is not an absence of an underlying mechanism. However, cell states may also reflect prior illness, immune activation and treatment. The order of cause and consequence needs further investigation. This is a mechanistic research resource, not a validated test for choosing an individual treatment or predicting a person’s future.'
 ],
 [
 'People with the same CVID diagnosis can experience very different combinations of infection, autoimmunity, lung disease and gut disease. It is natural to wonder whether those differences reveal which molecule is affected. This study brought clinical and genetic information from 405 people at one centre together to investigate that relationship. The question is about patterns across people, not diagnosing a reader from a symptom list.',
 'The investigators examined clinical manifestations, including autoimmune and organ complications, in relation to genetic findings. Observational comparisons can identify features that occur together and suggest useful questions for further investigation. They do not randomly assign treatment, and this analysis cannot establish which treatment would work best for a person. The nature of the comparison determines what the result can answer.',
 'Genetic findings provided explanations or clues for part of the cohort, but manifestations overlapped across genetic backgrounds. Clinical patterns did not identify particular genes neatly. An organ complication may support a discussion of genetic assessment without pointing to one unique cause. Conversely, not having a textbook presentation does not automatically exclude a genetic explanation. Symptoms remain important, but are not a molecular code.',
 'A variant needs to be interpreted with its inheritance, family information, immune measurements and evidence of biological function. A risk-associated variant and a well-supported causal defect are not the same category. TACI findings are an important example of why this distinction matters: a result can influence susceptibility without being sufficient to explain the whole condition. A gene name alone is not the interpretation.',
 'A more specific genetic diagnosis can help explain a pathway while ongoing care follows the person’s actual manifestations. The study population also reflects referral and testing decisions at one centre. Its proportions should not be presented as the chance that every patient will find a gene. Clinical and genetic information are most useful when they inform one another rather than compete as alternative explanations.'
 ],
 [
 'Rare-disease experiences are spread across hospitals and countries. Even an experienced team may see too few people with a particular feature to describe how it changes over many years. A registry brings records together in a more consistent format, creating opportunities to investigate uncommon diagnoses and outcomes. It extends the view beyond one centre without making every participating person’s circumstances identical.',
 'The ESID report covers registry information from 1994 to 2024, describing manifestations, treatments and outcomes in 30,628 people from 194 centres. It includes many types of inborn errors of immunity. The full number must not be labelled a CVID population, and results across all diagnoses cannot simply be applied to one person with CVID. Both scale and the mixture of conditions matter.',
 'A single test describes one moment; repeated records can reveal what happens later. They can help describe diagnostic delay, the emergence of complications, treatment experience and longer-term outcomes. These observations give future studies a more realistic starting point and may help formulate more specific questions. They are also a way for experiences that are individually uncommon to become visible to researchers.',
 'Participating centres do not represent every hospital, and registered patients do not represent everyone living with an immune disorder. Missing records and differences in investigation, referral and documentation affect comparisons. Two events occurring together do not establish causality. Comparing treatments is especially complicated when people with more severe illness are more likely to receive a particular intervention in the first place.',
 'Research is not limited to trying a new medicine. Registries, natural-history projects and sample studies can all contribute to understanding disease. Before deciding, read what information is requested, how much time is involved and how records will be used. Sharing an experience can be valuable, but whether to share it—and under which consent arrangements—remains a voluntary and informed choice.'
 ]
 ];
 paragraphs.forEach((texts,i)=>texts.forEach((text,j)=>items[i].sections[j][3]=text));
}
